"""Initial schema: all six modules, plus tenant-isolation RLS.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-06

Every business table carries `studio_id` and is covered by a row-level
security policy keyed to the caller's studio. The API resolves `studio_id`
server-side from the verified JWT and never accepts it from a request body,
so RLS here is defense-in-depth: it means a future direct-from-client read
path cannot leak across tenants even if the application layer is wrong.

`studio` itself is the tenant root, so its policy compares `id` rather than
`studio_id`.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


# Supabase authenticates end users as the `authenticated` role. The studio a
# request belongs to is carried in the JWT and read back out via the
# `request.jwt.claims` GUC that Supabase sets per connection.
TENANT_TABLES = (
    "booking",
    "brand_kit",
    "checklist_item",
    "checklist_template_item",
    "class_type",
    "export_record",
    "guest",
    "guest_allergy",
    "guest_celebration",
    "guest_credit",
    "host_badge",
    "host_user",
    "message_feedback",
    "scheduled_message",
    "session",
    "studio_settings",
    "waitlist_entry",
)


def _enable_rls() -> None:
    """Lock every table to the caller's studio."""
    op.execute("ALTER TABLE studio ENABLE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY studio_tenant_isolation ON studio
        USING (id = (current_setting('request.jwt.claims', true)::jsonb
                     ->> 'studio_id')::uuid)
        """
    )

    for table in TENANT_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (studio_id = (current_setting('request.jwt.claims', true)::jsonb
                                ->> 'studio_id')::uuid)
            """
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "studio",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studio")),
        sa.UniqueConstraint("slug", name=op.f("uq_studio_slug")),
    )
    op.create_table(
        "brand_kit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("primary_color", sa.String(length=9), nullable=True),
        sa.Column("accent_color", sa.String(length=9), nullable=True),
        sa.Column("instagram_handle", sa.String(length=60), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_brand_kit_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_kit")),
        sa.UniqueConstraint("studio_id", name="uq_brand_kit_studio_id"),
    )
    op.create_index(op.f("ix_brand_kit_studio_id"), "brand_kit", ["studio_id"], unique=False)
    op.create_table(
        "class_type",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "craft",
            sa.Enum("bento_cake", "pottery", "ceramic_painting", "custom", name="craftkind"),
            nullable=False,
        ),
        sa.Column("color_token", sa.String(length=24), nullable=False),
        sa.Column("default_seats", sa.Integer(), nullable=False),
        sa.Column("default_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "default_duration_minutes > 0", name=op.f("ck_class_type_duration_positive")
        ),
        sa.CheckConstraint(
            "default_seats >= 0", name=op.f("ck_class_type_default_seats_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_class_type_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_class_type")),
        sa.UniqueConstraint("studio_id", "name", name="uq_class_type_studio_id_name"),
    )
    op.create_index(op.f("ix_class_type_archived_at"), "class_type", ["archived_at"], unique=False)
    op.create_index(op.f("ix_class_type_studio_id"), "class_type", ["studio_id"], unique=False)
    op.create_table(
        "guest",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column(
            "preferred_channel",
            sa.Enum("sms", "whatsapp", "email", "in_app", name="messagechannel"),
            nullable=False,
        ),
        sa.Column("opted_out", sa.Boolean(), nullable=False),
        sa.Column("visit_count", sa.Integer(), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("memory_note", sa.Text(), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["studio_id"], ["studio.id"], name=op.f("fk_guest_studio_id_studio"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest")),
    )
    op.create_index(op.f("ix_guest_archived_at"), "guest", ["archived_at"], unique=False)
    op.create_index(op.f("ix_guest_studio_id"), "guest", ["studio_id"], unique=False)
    op.create_index(
        "ix_guest_studio_id_full_name", "guest", ["studio_id", "full_name"], unique=False
    )
    op.create_index(
        "uq_guest_studio_id_email",
        "guest",
        ["studio_id", "email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL AND archived_at IS NULL"),
    )
    op.create_index(
        "uq_guest_studio_id_phone",
        "guest",
        ["studio_id", "phone"],
        unique=True,
        postgresql_where=sa.text("phone IS NOT NULL AND archived_at IS NULL"),
    )
    op.create_table(
        "host_user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("auth_user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_host_user_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_host_user")),
        sa.UniqueConstraint("auth_user_id", name="uq_host_user_auth_user_id"),
        sa.UniqueConstraint("studio_id", "email", name="uq_host_user_studio_id_email"),
    )
    op.create_index(op.f("ix_host_user_auth_user_id"), "host_user", ["auth_user_id"], unique=False)
    op.create_index(op.f("ix_host_user_studio_id"), "host_user", ["studio_id"], unique=False)
    op.create_table(
        "studio_settings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("quiet_hours_start", sa.Time(), nullable=False),
        sa.Column("quiet_hours_end", sa.Time(), nullable=False),
        sa.Column("weekly_class_cap", sa.Integer(), nullable=True),
        sa.Column("rest_days", sa.ARRAY(sa.SmallInteger()), nullable=False),
        sa.Column(
            "default_voice",
            sa.Enum("soft_sweet", "chaotic_bestie", "clean_minimal", name="voicepreset"),
            nullable=False,
        ),
        sa.Column(
            "emoji_density", sa.Enum("none", "light", "full", name="emojidensity"), nullable=False
        ),
        sa.Column("show_greeting", sa.Boolean(), nullable=False),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_studio_settings_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studio_settings")),
        sa.UniqueConstraint("studio_id", name="uq_studio_settings_studio_id"),
    )
    op.create_index(
        op.f("ix_studio_settings_studio_id"), "studio_settings", ["studio_id"], unique=False
    )
    op.create_table(
        "checklist_template_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_type_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("hours_before", sa.Float(), nullable=False),
        sa.Column("phase", sa.Enum("prep", "post_class", name="checklistphase"), nullable=False),
        sa.Column("is_high_priority", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_checklist_template_item_position_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["class_type_id"],
            ["class_type.id"],
            name=op.f("fk_checklist_template_item_class_type_id_class_type"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_checklist_template_item_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_template_item")),
    )
    op.create_index(
        op.f("ix_checklist_template_item_class_type_id"),
        "checklist_template_item",
        ["class_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checklist_template_item_studio_id"),
        "checklist_template_item",
        ["studio_id"],
        unique=False,
    )
    op.create_table(
        "guest_allergy",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guest_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("preference", "intolerance", "allergy", "severe", name="allergyseverity"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guest.id"],
            name=op.f("fk_guest_allergy_guest_id_guest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_guest_allergy_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_allergy")),
    )
    op.create_index(op.f("ix_guest_allergy_guest_id"), "guest_allergy", ["guest_id"], unique=False)
    op.create_index(
        op.f("ix_guest_allergy_studio_id"), "guest_allergy", ["studio_id"], unique=False
    )
    op.create_table(
        "guest_celebration",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guest_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind", sa.Enum("birthday", "anniversary", name="celebrationkind"), nullable=False
        ),
        sa.Column("occurs_on", sa.Date(), nullable=False),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guest.id"],
            name=op.f("fk_guest_celebration_guest_id_guest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_guest_celebration_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_celebration")),
        sa.UniqueConstraint("guest_id", "kind", name="uq_guest_celebration_guest_id_kind"),
    )
    op.create_index(
        op.f("ix_guest_celebration_guest_id"), "guest_celebration", ["guest_id"], unique=False
    )
    op.create_index(
        op.f("ix_guest_celebration_studio_id"), "guest_celebration", ["studio_id"], unique=False
    )
    op.create_table(
        "session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("class_type_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "locked", "completed", "cancelled", name="sessionstatus"),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recurrence_group_id", sa.UUID(), nullable=True),
        sa.Column("sold_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_session_ends_after_start")),
        sa.CheckConstraint("seats >= 0", name=op.f("ck_session_seats_non_negative")),
        sa.ForeignKeyConstraint(
            ["class_type_id"],
            ["class_type.id"],
            name=op.f("fk_session_class_type_id_class_type"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_session_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
    )
    op.create_index(op.f("ix_session_archived_at"), "session", ["archived_at"], unique=False)
    op.create_index(op.f("ix_session_class_type_id"), "session", ["class_type_id"], unique=False)
    op.create_index(
        op.f("ix_session_recurrence_group_id"), "session", ["recurrence_group_id"], unique=False
    )
    op.create_index(op.f("ix_session_studio_id"), "session", ["studio_id"], unique=False)
    op.create_index(
        "ix_session_studio_id_starts_at", "session", ["studio_id", "starts_at"], unique=False
    )
    op.create_table(
        "booking",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("guest_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("confirmed", "attended", "no_show", "cancelled", name="bookingstatus"),
            nullable=False,
        ),
        sa.Column("table_number", sa.Integer(), nullable=True),
        sa.Column("sit_with_note", sa.String(length=200), nullable=True),
        sa.Column("booking_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "table_number IS NULL OR table_number > 0",
            name=op.f("ck_booking_table_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"], ["guest.id"], name=op.f("fk_booking_guest_id_guest"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_booking_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_booking_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_booking")),
    )
    op.create_index(op.f("ix_booking_guest_id"), "booking", ["guest_id"], unique=False)
    op.create_index(op.f("ix_booking_session_id"), "booking", ["session_id"], unique=False)
    op.create_index(op.f("ix_booking_studio_id"), "booking", ["studio_id"], unique=False)
    op.create_index("ix_booking_studio_id_status", "booking", ["studio_id", "status"], unique=False)
    op.create_index(
        "uq_booking_session_id_guest_id_active",
        "booking",
        ["session_id", "guest_id"],
        unique=True,
        postgresql_where=sa.text("status <> 'cancelled'"),
    )
    op.create_table(
        "checklist_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("text_template", sa.String(length=500), nullable=False),
        sa.Column("rendered_text", sa.String(length=500), nullable=False),
        sa.Column("last_quantity", sa.Integer(), nullable=True),
        sa.Column("hours_before", sa.Float(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phase", sa.Enum("prep", "post_class", name="checklistphase"), nullable=False),
        sa.Column("is_high_priority", sa.Boolean(), nullable=False),
        sa.Column("is_one_off", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("needs_attention_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_checklist_item_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_checklist_item_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_checklist_item_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checklist_item")),
    )
    op.create_index(
        "ix_checklist_item_pending_deadline",
        "checklist_item",
        ["studio_id", "deadline_at"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NULL"),
    )
    op.create_index(
        op.f("ix_checklist_item_session_id"), "checklist_item", ["session_id"], unique=False
    )
    op.create_index(
        "ix_checklist_item_session_id_deadline_at",
        "checklist_item",
        ["session_id", "deadline_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checklist_item_studio_id"), "checklist_item", ["studio_id"], unique=False
    )
    op.create_table(
        "export_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("theme", sa.String(length=60), nullable=False),
        sa.Column("layout", sa.String(length=40), nullable=False),
        sa.Column("roster_hash", sa.String(length=64), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_export_record_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_export_record_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_record")),
    )
    op.create_index(
        op.f("ix_export_record_session_id"), "export_record", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_export_record_studio_id"), "export_record", ["studio_id"], unique=False
    )
    op.create_table(
        "guest_credit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guest_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "redeemed", "expired", name="creditstatus"),
            nullable=False,
        ),
        sa.Column("issued_for_session_id", sa.UUID(), nullable=True),
        sa.Column("redeemed_for_session_id", sa.UUID(), nullable=True),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guest.id"],
            name=op.f("fk_guest_credit_guest_id_guest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issued_for_session_id"],
            ["session.id"],
            name=op.f("fk_guest_credit_issued_for_session_id_session"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["redeemed_for_session_id"],
            ["session.id"],
            name=op.f("fk_guest_credit_redeemed_for_session_id_session"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_guest_credit_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guest_credit")),
    )
    op.create_index(op.f("ix_guest_credit_guest_id"), "guest_credit", ["guest_id"], unique=False)
    op.create_index(op.f("ix_guest_credit_studio_id"), "guest_credit", ["studio_id"], unique=False)
    op.create_table(
        "host_badge",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_host_badge_session_id_session"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_host_badge_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_host_badge")),
        sa.UniqueConstraint("studio_id", "code", name="uq_host_badge_studio_id_code"),
    )
    op.create_index(op.f("ix_host_badge_studio_id"), "host_badge", ["studio_id"], unique=False)
    op.create_table(
        "scheduled_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("guest_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "guest_reminder",
                "guest_thank_you",
                "schedule_change",
                "waitlist_invite",
                "waitlist_position",
                "credit_issued",
                "birthday_offer",
                "host_nudge",
                name="messagekind",
            ),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("sms", "whatsapp", "email", "in_app", name="messagechannel"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "queued",
                "sending",
                "sent",
                "delivered",
                "failed",
                "cancelled",
                "skipped_opted_out",
                "skipped_no_contact",
                name="messagestatus",
            ),
            nullable=False,
        ),
        sa.Column("send_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("provider_message_id", sa.String(length=200), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guest.id"],
            name=op.f("fk_scheduled_message_guest_id_guest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_scheduled_message_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_scheduled_message_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_message")),
    )
    op.create_index(
        "ix_scheduled_message_due",
        "scheduled_message",
        ["status", "send_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('scheduled', 'queued')"),
    )
    op.create_index(
        op.f("ix_scheduled_message_guest_id"), "scheduled_message", ["guest_id"], unique=False
    )
    op.create_index(
        "ix_scheduled_message_guest_id_created_at",
        "scheduled_message",
        ["guest_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_message_session_id"), "scheduled_message", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_scheduled_message_studio_id"), "scheduled_message", ["studio_id"], unique=False
    )
    op.create_table(
        "waitlist_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("guest_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "invited",
                "accepted",
                "declined",
                "expired",
                "withdrawn",
                name="waitliststatus",
            ),
            nullable=False,
        ),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invite_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_waitlist_entry_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["guest_id"],
            ["guest.id"],
            name=op.f("fk_waitlist_entry_guest_id_guest"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_waitlist_entry_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_waitlist_entry_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waitlist_entry")),
        sa.UniqueConstraint("session_id", "guest_id", name="uq_waitlist_entry_session_id_guest_id"),
    )
    op.create_index(
        op.f("ix_waitlist_entry_guest_id"), "waitlist_entry", ["guest_id"], unique=False
    )
    op.create_index(
        op.f("ix_waitlist_entry_session_id"), "waitlist_entry", ["session_id"], unique=False
    )
    op.create_index(
        "ix_waitlist_entry_session_id_position",
        "waitlist_entry",
        ["session_id", "position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_waitlist_entry_studio_id"), "waitlist_entry", ["studio_id"], unique=False
    )
    op.create_table(
        "message_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("one_word", sa.String(length=60), nullable=True),
        sa.Column("studio_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["booking.id"],
            name=op.f("fk_message_feedback_booking_id_booking"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studio.id"],
            name=op.f("fk_message_feedback_studio_id_studio"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_feedback")),
        sa.UniqueConstraint("booking_id", name="uq_message_feedback_booking_id"),
    )
    op.create_index(
        op.f("ix_message_feedback_booking_id"), "message_feedback", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_studio_id"), "message_feedback", ["studio_id"], unique=False
    )
    # ### end Alembic commands ###

    _enable_rls()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_feedback")
    op.drop_table("waitlist_entry")
    op.drop_table("scheduled_message")
    op.drop_table("host_badge")
    op.drop_table("guest_credit")
    op.drop_table("export_record")
    op.drop_table("checklist_item")
    op.drop_table("booking")
    op.drop_table("session")
    op.drop_table("guest_celebration")
    op.drop_table("guest_allergy")
    op.drop_table("checklist_template_item")
    op.drop_table("studio_settings")
    op.drop_table("host_user")
    op.drop_table("guest")
    op.drop_table("class_type")
    op.drop_table("brand_kit")
    op.drop_table("studio")
    # ### end Alembic commands ###

    # Dropping a table leaves its enum type behind; remove them explicitly.
    sa.Enum(name="allergyseverity").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="bookingstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="celebrationkind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="checklistphase").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="craftkind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="creditstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="emojidensity").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="messagechannel").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="messagekind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="messagestatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="sessionstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="voicepreset").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="waitliststatus").drop(op.get_bind(), checkfirst=True)
